<?php
/**
 * UNIDA Chatbot Open Fix Installer
 * Upload to project root:
 * https://investoraccess.unidatechs.com/fix_chatbot_open.php
 * Delete after success.
 */

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

$root = __DIR__;
$results = [];

function add_result($name, $ok, $message = '') {
    global $results;
    $results[] = [$name, $ok, $message];
}

function ensure_dir($dir) {
    if (!is_dir($dir)) {
        mkdir($dir, 0755, true);
    }
}

function write_file_safe($relative, $contentB64) {
    global $root;
    $target = $root . DIRECTORY_SEPARATOR . str_replace('/', DIRECTORY_SEPARATOR, $relative);
    ensure_dir(dirname($target));

    $content = base64_decode($contentB64);
    if ($content === false) {
        add_result($relative, false, 'decode failed');
        return;
    }

    if (file_exists($target)) {
        @copy($target, $target . '.backup-' . date('Ymd-His'));
    }

    $ok = file_put_contents($target, $content) !== false;
    add_result($relative, $ok, $ok ? 'created/updated' : 'write failed');
}

$files = [
    'assets/js/rieta-chatbot.js' => 'KGZ1bmN0aW9uICgpIHsKICAgICd1c2Ugc3RyaWN0JzsKCiAgICBmdW5jdGlvbiByZWFkeShmbikgewogICAgICAgIGlmIChkb2N1bWVudC5yZWFkeVN0YXRlICE9PSAnbG9hZGluZycpIHsKICAgICAgICAgICAgZm4oKTsKICAgICAgICB9IGVsc2UgewogICAgICAgICAgICBkb2N1bWVudC5hZGRFdmVudExpc3RlbmVyKCdET01Db250ZW50TG9hZGVkJywgZm4pOwogICAgICAgIH0KICAgIH0KCiAgICByZWFkeShmdW5jdGlvbiAoKSB7CiAgICAgICAgY29uc3Qgcm9vdCA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoJyNyaWV0YUNoYXRib3QnKTsKICAgICAgICBpZiAoIXJvb3QpIHJldHVybjsKCiAgICAgICAgY29uc3QgdG9nZ2xlID0gZG9jdW1lbnQucXVlcnlTZWxlY3RvcignI3JpZXRhVG9nZ2xlJyk7CiAgICAgICAgY29uc3QgY2xvc2VCdG4gPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCcjcmlldGFDbG9zZScpOwogICAgICAgIGNvbnN0IGJvZHkgPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCcjcmlldGFCb2R5Jyk7CiAgICAgICAgY29uc3QgZm9ybSA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoJyNyaWV0YUZvcm0nKTsKICAgICAgICBjb25zdCBpbnB1dCA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoJyNyaWV0YUlucHV0Jyk7CiAgICAgICAgY29uc3Qgc3VwcG9ydEZvcm0gPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCcjcmlldGFTdXBwb3J0Rm9ybScpOwoKICAgICAgICBpZiAoIXRvZ2dsZSB8fCAhYm9keSB8fCAhZm9ybSB8fCAhaW5wdXQgfHwgIXN1cHBvcnRGb3JtKSByZXR1cm47CgogICAgICAgIGxldCBsYW5nID0gcm9vdC5kYXRhc2V0LmxhbmcgfHwgd2luZG93LlVOSURBX0xBTkcgfHwgJ2VuJzsKICAgICAgICBsZXQgc2VuZGluZyA9IGZhbHNlOwogICAgICAgIGxldCBsYXN0Q29uY2VybiA9ICcnOwoKICAgICAgICBjb25zdCBsYWJlbHMgPSB7CiAgICAgICAgICAgIGVuOiB7CiAgICAgICAgICAgICAgICB0eXBpbmc6ICdVbm55IGlzIHR5cGluZy4uLicsCiAgICAgICAgICAgICAgICBlcnJvcjogJ0Nvbm5lY3Rpb24gZXJyb3IuIFBsZWFzZSB0cnkgYWdhaW4uJywKICAgICAgICAgICAgICAgIGZpbGw6ICdQbGVhc2UgZmlsbCB5b3VyIGRldGFpbHMgYmVsb3cgc28gSSBjYW4gZm9yd2FyZCB0aGlzIHRvIGEgaHVtYW4gYWdlbnQuJwogICAgICAgICAgICB9LAogICAgICAgICAgICBzdzogewogICAgICAgICAgICAgICAgdHlwaW5nOiAnUmlldGEgYW5hYW5kaWthLi4uJywKICAgICAgICAgICAgICAgIGVycm9yOiAnS3VuYSBjaGFuZ2Ftb3RvIHlhIG11dW5nYW5pc2hvLiBUYWZhZGhhbGkgamFyaWJ1IHRlbmEuJywKICAgICAgICAgICAgICAgIGZpbGw6ICdUYWZhZGhhbGkgamF6YSB0YWFyaWZhIHpha28gaGFwYSBjaGluaSBpbGkgbml0dW1lIGt3YSBodW1hbiBhZ2VudC4nCiAgICAgICAgICAgIH0KICAgICAgICB9OwoKICAgICAgICBmdW5jdGlvbiBhZGRNZXNzYWdlKHRleHQsIHR5cGUpIHsKICAgICAgICAgICAgY29uc3QgZGl2ID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnZGl2Jyk7CiAgICAgICAgICAgIGRpdi5jbGFzc05hbWUgPSAncmlldGEtbXNnICcgKyAodHlwZSA9PT0gJ3VzZXInID8gJ3VzZXInIDogJ2JvdCcpOwogICAgICAgICAgICBkaXYudGV4dENvbnRlbnQgPSB0ZXh0OwogICAgICAgICAgICBib2R5LmFwcGVuZENoaWxkKGRpdik7CiAgICAgICAgICAgIGJvZHkuc2Nyb2xsVG9wID0gYm9keS5zY3JvbGxIZWlnaHQ7CiAgICAgICAgICAgIHJldHVybiBkaXY7CiAgICAgICAgfQoKICAgICAgICBmdW5jdGlvbiBzaG93U3VwcG9ydEZvcm0oY29uY2VybikgewogICAgICAgICAgICBpZiAoY29uY2VybikgewogICAgICAgICAgICAgICAgbGFzdENvbmNlcm4gPSBjb25jZXJuOwogICAgICAgICAgICAgICAgY29uc3QgdGV4dGFyZWEgPSBzdXBwb3J0Rm9ybS5xdWVyeVNlbGVjdG9yKCd0ZXh0YXJlYVtuYW1lPSJjb25jZXJuIl0nKTsKICAgICAgICAgICAgICAgIGlmICh0ZXh0YXJlYSAmJiAhdGV4dGFyZWEudmFsdWUudHJpbSgpKSB0ZXh0YXJlYS52YWx1ZSA9IGNvbmNlcm47CiAgICAgICAgICAgIH0KCiAgICAgICAgICAgIHN1cHBvcnRGb3JtLmNsYXNzTGlzdC5hZGQoJ3Nob3cnKTsKICAgICAgICAgICAgYm9keS5zY3JvbGxUb3AgPSBib2R5LnNjcm9sbEhlaWdodDsKICAgICAgICB9CgogICAgICAgIGZ1bmN0aW9uIG9wZW5Cb3QoKSB7CiAgICAgICAgICAgIHJvb3QuY2xhc3NMaXN0LmFkZCgnb3BlbicpOwogICAgICAgICAgICB0b2dnbGUuc2V0QXR0cmlidXRlKCdhcmlhLWV4cGFuZGVkJywgJ3RydWUnKTsKICAgICAgICAgICAgc2V0VGltZW91dChmdW5jdGlvbiAoKSB7CiAgICAgICAgICAgICAgICBpbnB1dC5mb2N1cygpOwogICAgICAgICAgICB9LCA4MCk7CiAgICAgICAgfQoKICAgICAgICBmdW5jdGlvbiBjbG9zZUJvdCgpIHsKICAgICAgICAgICAgcm9vdC5jbGFzc0xpc3QucmVtb3ZlKCdvcGVuJyk7CiAgICAgICAgICAgIHRvZ2dsZS5zZXRBdHRyaWJ1dGUoJ2FyaWEtZXhwYW5kZWQnLCAnZmFsc2UnKTsKICAgICAgICB9CgogICAgICAgIHRvZ2dsZS5hZGRFdmVudExpc3RlbmVyKCdjbGljaycsIGZ1bmN0aW9uIChldmVudCkgewogICAgICAgICAgICBldmVudC5wcmV2ZW50RGVmYXVsdCgpOwogICAgICAgICAgICBldmVudC5zdG9wUHJvcGFnYXRpb24oKTsKCiAgICAgICAgICAgIGlmIChyb290LmNsYXNzTGlzdC5jb250YWlucygnb3BlbicpKSB7CiAgICAgICAgICAgICAgICBjbG9zZUJvdCgpOwogICAgICAgICAgICB9IGVsc2UgewogICAgICAgICAgICAgICAgb3BlbkJvdCgpOwogICAgICAgICAgICB9CiAgICAgICAgfSk7CgogICAgICAgIGlmIChjbG9zZUJ0bikgewogICAgICAgICAgICBjbG9zZUJ0bi5hZGRFdmVudExpc3RlbmVyKCdjbGljaycsIGZ1bmN0aW9uIChldmVudCkgewogICAgICAgICAgICAgICAgZXZlbnQucHJldmVudERlZmF1bHQoKTsKICAgICAgICAgICAgICAgIGNsb3NlQm90KCk7CiAgICAgICAgICAgIH0pOwogICAgICAgIH0KCiAgICAgICAgYXN5bmMgZnVuY3Rpb24gY2FsbEJvdChwYXlsb2FkKSB7CiAgICAgICAgICAgIGNvbnN0IGNvbnRyb2xsZXIgPSBuZXcgQWJvcnRDb250cm9sbGVyKCk7CiAgICAgICAgICAgIGNvbnN0IHRpbWVvdXQgPSBzZXRUaW1lb3V0KGZ1bmN0aW9uICgpIHsKICAgICAgICAgICAgICAgIGNvbnRyb2xsZXIuYWJvcnQoKTsKICAgICAgICAgICAgfSwgMTIwMDApOwoKICAgICAgICAgICAgdHJ5IHsKICAgICAgICAgICAgICAgIGNvbnN0IHJlc3BvbnNlID0gYXdhaXQgZmV0Y2goKHdpbmRvdy5VTklEQV9CQVNFX1VSTCB8fCAnLycpICsgJ2FwaS9yaWV0YS1jaGF0Ym90LnBocCcsIHsKICAgICAgICAgICAgICAgICAgICBtZXRob2Q6ICdQT1NUJywKICAgICAgICAgICAgICAgICAgICBoZWFkZXJzOiB7J0NvbnRlbnQtVHlwZSc6ICdhcHBsaWNhdGlvbi9qc29uJ30sCiAgICAgICAgICAgICAgICAgICAgc2lnbmFsOiBjb250cm9sbGVyLnNpZ25hbCwKICAgICAgICAgICAgICAgICAgICBib2R5OiBKU09OLnN0cmluZ2lmeShwYXlsb2FkKQogICAgICAgICAgICAgICAgfSk7CgogICAgICAgICAgICAgICAgY2xlYXJUaW1lb3V0KHRpbWVvdXQpOwoKICAgICAgICAgICAgICAgIGlmICghcmVzcG9uc2Uub2spIHsKICAgICAgICAgICAgICAgICAgICByZXR1cm4ge3N1Y2Nlc3M6IGZhbHNlLCByZXBseTogKGxhYmVsc1tsYW5nXSB8fCBsYWJlbHMuZW4pLmVycm9yfTsKICAgICAgICAgICAgICAgIH0KCiAgICAgICAgICAgICAgICByZXR1cm4gYXdhaXQgcmVzcG9uc2UuanNvbigpOwogICAgICAgICAgICB9IGNhdGNoIChlcnJvcikgewogICAgICAgICAgICAgICAgY2xlYXJUaW1lb3V0KHRpbWVvdXQpOwogICAgICAgICAgICAgICAgcmV0dXJuIHtzdWNjZXNzOiBmYWxzZSwgcmVwbHk6IChsYWJlbHNbbGFuZ10gfHwgbGFiZWxzLmVuKS5lcnJvcn07CiAgICAgICAgICAgIH0KICAgICAgICB9CgogICAgICAgIGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3JBbGwoJ1tkYXRhLXRvcGljXScpLmZvckVhY2goZnVuY3Rpb24gKGJ1dHRvbikgewogICAgICAgICAgICBidXR0b24uYWRkRXZlbnRMaXN0ZW5lcignY2xpY2snLCBhc3luYyBmdW5jdGlvbiAoKSB7CiAgICAgICAgICAgICAgICBpZiAoc2VuZGluZykgcmV0dXJuOwoKICAgICAgICAgICAgICAgIGNvbnN0IHRvcGljID0gYnV0dG9uLmRhdGFzZXQudG9waWM7CiAgICAgICAgICAgICAgICBjb25zdCBsYWJlbCA9IGJ1dHRvbi50ZXh0Q29udGVudC50cmltKCk7CgogICAgICAgICAgICAgICAgYWRkTWVzc2FnZShsYWJlbCwgJ3VzZXInKTsKCiAgICAgICAgICAgICAgICBpZiAodG9waWMgPT09ICdodW1hbl9hZ2VudCcpIHsKICAgICAgICAgICAgICAgICAgICBhZGRNZXNzYWdlKChsYWJlbHNbbGFuZ10gfHwgbGFiZWxzLmVuKS5maWxsLCAnYm90Jyk7CiAgICAgICAgICAgICAgICAgICAgc2hvd1N1cHBvcnRGb3JtKCcnKTsKICAgICAgICAgICAgICAgICAgICByZXR1cm47CiAgICAgICAgICAgICAgICB9CgogICAgICAgICAgICAgICAgc2VuZGluZyA9IHRydWU7CiAgICAgICAgICAgICAgICBjb25zdCBsb2FkaW5nID0gYWRkTWVzc2FnZSgobGFiZWxzW2xhbmddIHx8IGxhYmVscy5lbikudHlwaW5nLCAnYm90Jyk7CgogICAgICAgICAgICAgICAgY29uc3QgZGF0YSA9IGF3YWl0IGNhbGxCb3QoewogICAgICAgICAgICAgICAgICAgIGFjdGlvbjogJ21lc3NhZ2UnLAogICAgICAgICAgICAgICAgICAgIHRvcGljOiB0b3BpYywKICAgICAgICAgICAgICAgICAgICBtZXNzYWdlOiBsYWJlbCwKICAgICAgICAgICAgICAgICAgICBsYW5nOiBsYW5nCiAgICAgICAgICAgICAgICB9KTsKCiAgICAgICAgICAgICAgICBsb2FkaW5nLnJlbW92ZSgpOwogICAgICAgICAgICAgICAgbGFuZyA9IGRhdGEubGFuZyB8fCBsYW5nOwogICAgICAgICAgICAgICAgYWRkTWVzc2FnZShkYXRhLnJlcGx5IHx8IChsYWJlbHNbbGFuZ10gfHwgbGFiZWxzLmVuKS5lcnJvciwgJ2JvdCcpOwoKICAgICAgICAgICAgICAgIGlmIChkYXRhLm5lZWRzX2h1bWFuX2RldGFpbHMpIHsKICAgICAgICAgICAgICAgICAgICBzaG93U3VwcG9ydEZvcm0obGFiZWwpOwogICAgICAgICAgICAgICAgfQoKICAgICAgICAgICAgICAgIHNlbmRpbmcgPSBmYWxzZTsKICAgICAgICAgICAgfSk7CiAgICAgICAgfSk7CgogICAgICAgIGZvcm0uYWRkRXZlbnRMaXN0ZW5lcignc3VibWl0JywgYXN5bmMgZnVuY3Rpb24gKGV2ZW50KSB7CiAgICAgICAgICAgIGV2ZW50LnByZXZlbnREZWZhdWx0KCk7CgogICAgICAgICAgICBpZiAoc2VuZGluZykgcmV0dXJuOwoKICAgICAgICAgICAgY29uc3QgdGV4dCA9IGlucHV0LnZhbHVlLnRyaW0oKTsKICAgICAgICAgICAgaWYgKCF0ZXh0KSByZXR1cm47CgogICAgICAgICAgICBpbnB1dC52YWx1ZSA9ICcnOwogICAgICAgICAgICBsYXN0Q29uY2VybiA9IHRleHQ7CiAgICAgICAgICAgIGFkZE1lc3NhZ2UodGV4dCwgJ3VzZXInKTsKCiAgICAgICAgICAgIHNlbmRpbmcgPSB0cnVlOwogICAgICAgICAgICBjb25zdCBsb2FkaW5nID0gYWRkTWVzc2FnZSgobGFiZWxzW2xhbmddIHx8IGxhYmVscy5lbikudHlwaW5nLCAnYm90Jyk7CgogICAgICAgICAgICBjb25zdCBkYXRhID0gYXdhaXQgY2FsbEJvdCh7CiAgICAgICAgICAgICAgICBhY3Rpb246ICdtZXNzYWdlJywKICAgICAgICAgICAgICAgIG1lc3NhZ2U6IHRleHQsCiAgICAgICAgICAgICAgICBsYW5nOiBsYW5nCiAgICAgICAgICAgIH0pOwoKICAgICAgICAgICAgbG9hZGluZy5yZW1vdmUoKTsKICAgICAgICAgICAgbGFuZyA9IGRhdGEubGFuZyB8fCBsYW5nOwogICAgICAgICAgICBhZGRNZXNzYWdlKGRhdGEucmVwbHkgfHwgKGxhYmVsc1tsYW5nXSB8fCBsYWJlbHMuZW4pLmVycm9yLCAnYm90Jyk7CgogICAgICAgICAgICBpZiAoZGF0YS5uZWVkc19odW1hbl9kZXRhaWxzKSB7CiAgICAgICAgICAgICAgICBzaG93U3VwcG9ydEZvcm0odGV4dCk7CiAgICAgICAgICAgIH0KCiAgICAgICAgICAgIHNlbmRpbmcgPSBmYWxzZTsKICAgICAgICB9KTsKCiAgICAgICAgc3VwcG9ydEZvcm0uYWRkRXZlbnRMaXN0ZW5lcignc3VibWl0JywgYXN5bmMgZnVuY3Rpb24gKGV2ZW50KSB7CiAgICAgICAgICAgIGV2ZW50LnByZXZlbnREZWZhdWx0KCk7CgogICAgICAgICAgICBpZiAoc2VuZGluZykgcmV0dXJuOwoKICAgICAgICAgICAgY29uc3QgZm9ybURhdGEgPSBuZXcgRm9ybURhdGEoc3VwcG9ydEZvcm0pOwogICAgICAgICAgICBjb25zdCBwYXlsb2FkID0gewogICAgICAgICAgICAgICAgYWN0aW9uOiAnc3VwcG9ydF9yZXF1ZXN0JywKICAgICAgICAgICAgICAgIGxhbmc6IGxhbmcsCiAgICAgICAgICAgICAgICBmdWxsX25hbWU6IGZvcm1EYXRhLmdldCgnZnVsbF9uYW1lJykgfHwgJycsCiAgICAgICAgICAgICAgICBlbWFpbDogZm9ybURhdGEuZ2V0KCdlbWFpbCcpIHx8ICcnLAogICAgICAgICAgICAgICAgcGhvbmU6IGZvcm1EYXRhLmdldCgncGhvbmUnKSB8fCAnJywKICAgICAgICAgICAgICAgIGNvbmNlcm46IGZvcm1EYXRhLmdldCgnY29uY2VybicpIHx8IGxhc3RDb25jZXJuIHx8ICcnCiAgICAgICAgICAgIH07CgogICAgICAgICAgICBzZW5kaW5nID0gdHJ1ZTsKICAgICAgICAgICAgY29uc3QgbG9hZGluZyA9IGFkZE1lc3NhZ2UoKGxhYmVsc1tsYW5nXSB8fCBsYWJlbHMuZW4pLnR5cGluZywgJ2JvdCcpOwoKICAgICAgICAgICAgY29uc3QgZGF0YSA9IGF3YWl0IGNhbGxCb3QocGF5bG9hZCk7CgogICAgICAgICAgICBsb2FkaW5nLnJlbW92ZSgpOwogICAgICAgICAgICBsYW5nID0gZGF0YS5sYW5nIHx8IGxhbmc7CiAgICAgICAgICAgIGFkZE1lc3NhZ2UoZGF0YS5yZXBseSB8fCAobGFiZWxzW2xhbmddIHx8IGxhYmVscy5lbikuZXJyb3IsICdib3QnKTsKCiAgICAgICAgICAgIGlmIChkYXRhLnN1Y2Nlc3MpIHsKICAgICAgICAgICAgICAgIHN1cHBvcnRGb3JtLnJlc2V0KCk7CiAgICAgICAgICAgICAgICBzdXBwb3J0Rm9ybS5jbGFzc0xpc3QucmVtb3ZlKCdzaG93Jyk7CiAgICAgICAgICAgIH0KCiAgICAgICAgICAgIHNlbmRpbmcgPSBmYWxzZTsKICAgICAgICB9KTsKICAgIH0pOwp9KSgpOw==',
    'assets/css/rieta-chatbot.css' => 'LnJpZXRhLWNoYXRib3R7cG9zaXRpb246Zml4ZWQhaW1wb3J0YW50O3JpZ2h0OjE4cHghaW1wb3J0YW50O2JvdHRvbToxOHB4IWltcG9ydGFudDt6LWluZGV4Ojk5OTk5OSFpbXBvcnRhbnQ7Zm9udC1mYW1pbHk6SW50ZXIsQXJpYWwsc2Fucy1zZXJpZn0ucmlldGEtdG9nZ2xle2JvcmRlcjowO2JvcmRlci1yYWRpdXM6OTk5cHg7YmFja2dyb3VuZDojMEE1REI3O2NvbG9yOiNmZmY7Ym94LXNoYWRvdzowIDE0cHggMzZweCByZ2JhKDgsNTksMTIyLC4yMik7cGFkZGluZzoxMnB4IDE2cHg7ZGlzcGxheTpmbGV4O2FsaWduLWl0ZW1zOmNlbnRlcjtnYXA6OHB4O2ZvbnQtd2VpZ2h0OjkwMDtjdXJzb3I6cG9pbnRlcjtmb250LXNpemU6MTRweH0ucmlldGEtcGFuZWx7ZGlzcGxheTpub25lO3Bvc2l0aW9uOmFic29sdXRlO3JpZ2h0OjA7Ym90dG9tOjU2cHg7d2lkdGg6bWluKDM3MHB4LGNhbGMoMTAwdncgLSAyOHB4KSk7YmFja2dyb3VuZDojZmZmO2JvcmRlcjoxcHggc29saWQgcmdiYSg4LDU5LDEyMiwuMTApO2JvcmRlci1yYWRpdXM6MjBweDtib3gtc2hhZG93OjAgMjJweCA2MHB4IHJnYmEoOCw1OSwxMjIsLjIwKTtvdmVyZmxvdzpoaWRkZW59LnJpZXRhLWNoYXRib3Qub3BlbiAucmlldGEtcGFuZWx7ZGlzcGxheTpibG9jayFpbXBvcnRhbnR9LnJpZXRhLWhlYWR7cGFkZGluZzoxNHB4IDE1cHg7YmFja2dyb3VuZDpsaW5lYXItZ3JhZGllbnQoMTM1ZGVnLCMwODNCN0EsIzBBNURCNyk7Y29sb3I6I2ZmZjtkaXNwbGF5OmZsZXg7anVzdGlmeS1jb250ZW50OnNwYWNlLWJldHdlZW47YWxpZ24taXRlbXM6ZmxleC1zdGFydDtnYXA6MTJweH0ucmlldGEtaGVhZCBzdHJvbmd7ZGlzcGxheTpibG9jaztmb250LXNpemU6MThweDtsaW5lLWhlaWdodDoxLjJ9LnJpZXRhLWhlYWQgc21hbGx7ZGlzcGxheTpibG9jaztmb250LXNpemU6MTJweDtsaW5lLWhlaWdodDoxLjQ1O29wYWNpdHk6Ljk7bWFyZ2luLXRvcDo0cHh9LnJpZXRhLWhlYWQgYnV0dG9ue2JvcmRlcjowO2JhY2tncm91bmQ6cmdiYSgyNTUsMjU1LDI1NSwuMTYpO2NvbG9yOiNmZmY7d2lkdGg6MzRweDtoZWlnaHQ6MzRweDtib3JkZXItcmFkaXVzOjEycHg7Y3Vyc29yOnBvaW50ZXI7ZmxleDowIDAgYXV0b30ucmlldGEtYm9keXtoZWlnaHQ6MzE1cHg7b3ZlcmZsb3cteTphdXRvO3BhZGRpbmc6MTJweDtiYWNrZ3JvdW5kOiNmOGZjZmY7ZGlzcGxheTpmbGV4O2ZsZXgtZGlyZWN0aW9uOmNvbHVtbjtnYXA6OXB4O3Njcm9sbC1iZWhhdmlvcjpzbW9vdGh9LnJpZXRhLW1zZ3twYWRkaW5nOjEwcHggMTJweDtib3JkZXItcmFkaXVzOjE0cHg7Zm9udC1zaXplOjEzLjVweDtsaW5lLWhlaWdodDoxLjU7bWF4LXdpZHRoOjkwJTt3b3JkLXdyYXA6YnJlYWstd29yZH0ucmlldGEtbXNnLmJvdHtiYWNrZ3JvdW5kOiNmZmY7Y29sb3I6IzM0NDA1NDtib3JkZXI6MXB4IHNvbGlkIHJnYmEoOCw1OSwxMjIsLjA4KTthbGlnbi1zZWxmOmZsZXgtc3RhcnR9LnJpZXRhLW1zZy51c2Vye2JhY2tncm91bmQ6IzBBNURCNztjb2xvcjojZmZmO2FsaWduLXNlbGY6ZmxleC1lbmR9LnJpZXRhLXRvcGljc3tkaXNwbGF5OmZsZXg7ZmxleC13cmFwOndyYXA7Z2FwOjdweDttYXJnaW4tdG9wOjJweH0ucmlldGEtdG9waWNzIGJ1dHRvbntib3JkZXI6MXB4IHNvbGlkIHJnYmEoMTAsOTMsMTgzLC4xNik7YmFja2dyb3VuZDojZmZmO2NvbG9yOiMwODNCN0E7Ym9yZGVyLXJhZGl1czo5OTlweDtwYWRkaW5nOjhweCAxMHB4O2ZvbnQtc2l6ZToxMi41cHg7Zm9udC13ZWlnaHQ6ODUwO2N1cnNvcjpwb2ludGVyfS5yaWV0YS10b3BpY3MgYnV0dG9uOmhvdmVye2JhY2tncm91bmQ6I2VlZjdmYn0ucmlldGEtZm9ybXtkaXNwbGF5OmZsZXg7Z2FwOjhweDtwYWRkaW5nOjEwcHg7YmFja2dyb3VuZDojZmZmO2JvcmRlci10b3A6MXB4IHNvbGlkIHJnYmEoOCw1OSwxMjIsLjA4KX0ucmlldGEtZm9ybSBpbnB1dHtmbGV4OjE7Ym9yZGVyOjFweCBzb2xpZCByZ2JhKDgsNTksMTIyLC4xNCk7Ym9yZGVyLXJhZGl1czoxNHB4O3BhZGRpbmc6MTFweCAxMnB4O291dGxpbmU6bm9uZTtmb250LXNpemU6MTRweDttaW4td2lkdGg6MH0ucmlldGEtZm9ybSBpbnB1dDpmb2N1c3tib3JkZXItY29sb3I6IzBBNURCNztib3gtc2hhZG93OjAgMCAwIDRweCByZ2JhKDEwLDkzLDE4MywuMDgpfS5yaWV0YS1mb3JtIGJ1dHRvbntib3JkZXI6MDtiYWNrZ3JvdW5kOiMyMEM5OTc7Y29sb3I6I2ZmZjtib3JkZXItcmFkaXVzOjE0cHg7d2lkdGg6NDRweDtjdXJzb3I6cG9pbnRlcjtmbGV4OjAgMCBhdXRvfS5yaWV0YS1zdXBwb3J0LWZvcm17ZGlzcGxheTpub25lO2dhcDo4cHg7cGFkZGluZzoxMnB4O2JhY2tncm91bmQ6I2ZmZjtib3JkZXItdG9wOjFweCBzb2xpZCByZ2JhKDgsNTksMTIyLC4wOCl9LnJpZXRhLXN1cHBvcnQtZm9ybS5zaG93e2Rpc3BsYXk6Z3JpZH0ucmlldGEtc3VwcG9ydC1mb3JtIHN0cm9uZ3tmb250LXNpemU6MTNweDtjb2xvcjojMDgzQjdBfS5yaWV0YS1zdXBwb3J0LWZvcm0gaW5wdXQsLnJpZXRhLXN1cHBvcnQtZm9ybSB0ZXh0YXJlYXt3aWR0aDoxMDAlO2JvcmRlcjoxcHggc29saWQgcmdiYSg4LDU5LDEyMiwuMTQpO2JvcmRlci1yYWRpdXM6MTJweDtwYWRkaW5nOjEwcHggMTFweDtmb250LXNpemU6MTNweDtvdXRsaW5lOm5vbmU7Ym94LXNpemluZzpib3JkZXItYm94fS5yaWV0YS1zdXBwb3J0LWZvcm0gdGV4dGFyZWF7bWluLWhlaWdodDo3NHB4O3Jlc2l6ZTp2ZXJ0aWNhbH0ucmlldGEtc3VwcG9ydC1mb3JtIGJ1dHRvbntib3JkZXI6MDtiYWNrZ3JvdW5kOiMwQTVEQjc7Y29sb3I6I2ZmZjtib3JkZXItcmFkaXVzOjEzcHg7cGFkZGluZzoxMXB4IDEycHg7Zm9udC13ZWlnaHQ6OTAwO2N1cnNvcjpwb2ludGVyfS5sYW5ndWFnZS1zd2l0Y2h7ZGlzcGxheTppbmxpbmUtZmxleDthbGlnbi1pdGVtczpjZW50ZXI7Z2FwOjRweDtiYWNrZ3JvdW5kOiNmOGZjZmY7Ym9yZGVyOjFweCBzb2xpZCByZ2JhKDgsNTksMTIyLC4xMCk7Ym9yZGVyLXJhZGl1czo5OTlweDtwYWRkaW5nOjRweH0ubGFuZ3VhZ2Utc3dpdGNoIGF7ZGlzcGxheTppbmxpbmUtZmxleDthbGlnbi1pdGVtczpjZW50ZXI7anVzdGlmeS1jb250ZW50OmNlbnRlcjttaW4td2lkdGg6MzRweDtoZWlnaHQ6MjhweDtib3JkZXItcmFkaXVzOjk5OXB4O2ZvbnQtd2VpZ2h0OjkwMDtmb250LXNpemU6MTJweDtjb2xvcjojMDgzQjdBO3RleHQtZGVjb3JhdGlvbjpub25lfS5sYW5ndWFnZS1zd2l0Y2ggYS5hY3RpdmV7YmFja2dyb3VuZDojMEE1REI3O2NvbG9yOiNmZmZ9Lm5hdi1hY3Rpb25zIC5sYW5ndWFnZS1zd2l0Y2h7bWFyZ2luLXJpZ2h0OjZweH1AbWVkaWEobWF4LXdpZHRoOjY0MHB4KXsucmlldGEtY2hhdGJvdHtyaWdodDoxMnB4IWltcG9ydGFudDtib3R0b206MTJweCFpbXBvcnRhbnR9LnJpZXRhLXBhbmVse2JvdHRvbTo1NHB4O3dpZHRoOmNhbGMoMTAwdncgLSAyNHB4KX0ucmlldGEtYm9keXtoZWlnaHQ6MjkwcHh9LnJpZXRhLXRvZ2dsZXtwYWRkaW5nOjExcHggMTRweH0ubGFuZ3VhZ2Utc3dpdGNoe21hcmdpbjo4cHggMH19',
];

foreach ($files as $relative => $contentB64) {
    write_file_safe($relative, $contentB64);
}

try {
    $footerPath = $root . '/includes/footer.php';

    if (file_exists($footerPath)) {
        $footer = file_get_contents($footerPath);

        $footer = preg_replace('/<!-- RIETA_CHATBOT_START -->.*?<!-- RIETA_CHATBOT_END -->/s', '', $footer);
        $footer = preg_replace('/<!-- UNIDA_CHATBOT_LANGUAGE_START -->.*?<!-- UNIDA_CHATBOT_LANGUAGE_END -->/s', '', $footer);

        $block = <<<'PHPBLOCK'
<!-- UNIDA_CHATBOT_LANGUAGE_START -->
<?php
$chatbotWidget = __DIR__ . '/components/rieta-chatbot-widget.php';

if (file_exists($chatbotWidget)) {
    include $chatbotWidget;
}
?>

<link rel="stylesheet" href="<?= e(asset_url('css/rieta-chatbot.css')); ?>">

<script>
    window.UNIDA_BASE_URL = "<?= e(BASE_URL); ?>";
    window.UNIDA_LANG = "<?= function_exists('current_language') ? e(current_language()) : 'en'; ?>";
</script>

<script src="<?= e(asset_url('js/rieta-chatbot.js')); ?>"></script>
<!-- UNIDA_CHATBOT_LANGUAGE_END -->
PHPBLOCK;

        $mainScript = '<script src="<?= e(asset_url(\'js/main.js\')); ?>"></script>';

        if (strpos($footer, $mainScript) !== false) {
            $footer = str_replace($mainScript, $block . "\n\n" . $mainScript, $footer);
        } elseif (strpos($footer, '</body>') !== false) {
            $footer = str_replace('</body>', $block . "\n</body>", $footer);
        } else {
            $footer .= "\n" . $block . "\n";
        }

        @copy($footerPath, $footerPath . '.backup-' . date('Ymd-His'));
        $ok = file_put_contents($footerPath, $footer) !== false;
        add_result('includes/footer.php', $ok, $ok ? 'old duplicate blocks removed and clean chatbot block added' : 'failed');
    } else {
        add_result('includes/footer.php', false, 'footer.php not found');
    }
} catch (Throwable $e) {
    add_result('includes/footer.php', false, $e->getMessage());
}
?>
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Chatbot Open Fix</title>
<style>
body{font-family:Arial,sans-serif;background:#f2f6f9;color:#1d2939;padding:30px}
.box{max-width:980px;margin:auto;background:#fff;border-radius:18px;padding:24px;box-shadow:0 18px 44px rgba(8,59,122,.12)}
.ok{color:#0E7C6B;font-weight:800}.fail{color:#991b1b;font-weight:800}
li{padding:8px 0;border-bottom:1px solid #eef2f6}code{background:#eef7fb;padding:3px 6px;border-radius:6px}
.warn{background:#fff5f5;border-left:5px solid #dc2626;padding:14px;border-radius:12px;margin-top:18px}
</style>
</head>
<body>
<div class="box">
<h1>Chatbot Open Fix Result</h1>
<ul>
<?php foreach ($results as $row): ?>
<li><span class="<?= $row[1] ? 'ok' : 'fail'; ?>"><?= $row[1] ? 'OK' : 'FAILED'; ?></span> <code><?= htmlspecialchars($row[0], ENT_QUOTES, 'UTF-8'); ?></code> <?= htmlspecialchars($row[2], ENT_QUOTES, 'UTF-8'); ?></li>
<?php endforeach; ?>
</ul>
<div class="warn"><strong>Important:</strong> Delete <code>fix_chatbot_open.php</code> after success.</div>
</div>
</body>
</html>
