<?php

return [
    'default_role' => 'business',
    'roles' => [
        'business' => [
            'label' => 'SME / Startup / Company',
            'area' => 'business',
            'dashboard_uri' => '/business/dashboard.php',
            'modules' => [
                'overview' => ['label' => 'Dashboard', 'description' => 'Overview of business status, verification progress and activity', 'uri' => '/business/dashboard.php'],
                'profile' => ['label' => 'Business Profile', 'description' => 'Manage company info, sector, location, stage and funding needs', 'uri' => '/business/profile.php'],
                'readiness' => ['label' => 'Readiness', 'description' => 'Track readiness score and preparation steps before investor engagement', 'uri' => '/business/readiness.php'],
                'documents' => ['label' => 'Documents', 'description' => 'Upload and manage documents required for verification', 'uri' => '/business/documents.php'],
                'opportunities' => ['label' => 'Opportunities', 'description' => 'Create and manage funding requests and investor visibility', 'uri' => '/business/opportunities.php'],
                'connections' => ['label' => 'Connections', 'description' => 'Track investor interests, referrals and partner connections', 'uri' => '/business/connections.php'],
                'insights' => ['label' => 'Insights', 'description' => 'View sector updates, reports and market information', 'uri' => '/business/insights.php'],
                'messages' => ['label' => 'Messages', 'description' => 'Communicate with investors, stakeholders and the platform', 'uri' => '/business/messages.php'],
                'settings' => ['label' => 'Settings', 'description' => 'Manage account preferences, security and contact details', 'uri' => '/business/settings.php'],
            ],
        ],
        'investor' => [
            'label' => 'Local & foreign investors',
            'area' => 'investor',
            'dashboard_uri' => '/investor/dashboard.php',
            'modules' => [
                'overview' => ['label' => 'Dashboard', 'description' => 'Overview of pipeline activity, shortlist and recent opportunities', 'uri' => '/investor/dashboard.php'],
                'profile' => ['label' => 'Investor Profile', 'description' => 'Manage preferred sectors, regions, ticket size and focus areas', 'uri' => '/investor/profile.php'],
                'discover' => ['label' => 'Discover', 'description' => 'Explore published opportunities across sectors and regions', 'uri' => '/investor/discover.php'],
                'verified-businesses' => ['label' => 'Verified Businesses', 'description' => 'Browse businesses that have passed verification', 'uri' => '/investor/verified-businesses.php'],
                'shortlist' => ['label' => 'Shortlist', 'description' => 'Save and manage opportunities of interest', 'uri' => '/investor/shortlist.php'],
                'my-projects' => ['label' => 'My Projects', 'description' => 'Accepted opportunities with business contact information', 'uri' => '/investor/my-projects.php'],
                'pipeline' => ['label' => 'Pipeline', 'description' => 'Track deals from saved through to decision stage', 'uri' => '/investor/pipeline.php'],
                'meetings' => ['label' => 'Meetings', 'description' => 'Manage discovery calls, due diligence and stakeholder sessions', 'uri' => '/investor/meetings.php'],
                'insights' => ['label' => 'Insights', 'description' => 'View sector briefs, reports and investment decision support', 'uri' => '/investor/insights.php'],
                'messages' => ['label' => 'Messages', 'description' => 'Communicate with businesses, stakeholders and the platform', 'uri' => '/investor/messages.php'],
                'settings' => ['label' => 'Settings', 'description' => 'Manage account preferences, access and notification settings', 'uri' => '/investor/settings.php'],
            ],
        ],
        'stakeholder' => [
            'label' => 'Banks, hubs, govt, DFIs (TIC, CRDB, NMB, PSST)',
            'area' => 'stakeholder',
            'dashboard_uri' => '/stakeholder/dashboard.php',
            'modules' => [
                'overview' => ['label' => 'Dashboard', 'description' => 'Overview of ecosystem activity, recommendations and connections', 'uri' => '/stakeholder/dashboard.php'],
                'profile' => ['label' => 'Organisation Profile', 'description' => 'Manage institution, mandate, sector focus and contact information', 'uri' => '/stakeholder/profile.php'],
                'businesses' => ['label' => 'Review Businesses', 'description' => 'Browse and assess business profiles, readiness and support needs', 'uri' => '/stakeholder/businesses.php'],
                'recommendations' => ['label' => 'Recommendations', 'description' => 'Connect businesses to investors, programs or support partners', 'uri' => '/stakeholder/recommendations.php'],
                'connections' => ['label' => 'Connections', 'description' => 'Track referrals, accepted connections and collaboration records', 'uri' => '/stakeholder/connections.php'],
                'follow-ups' => ['label' => 'Follow-ups', 'description' => 'Manage outstanding actions, review notes and coordination tasks', 'uri' => '/stakeholder/follow-ups.php'],
                'reports' => ['label' => 'Reports', 'description' => 'Prepare impact summaries, ecosystem notes and stakeholder reports', 'uri' => '/stakeholder/reports.php'],
                'insights' => ['label' => 'Insights', 'description' => 'View analytics, updates and decision-support information', 'uri' => '/stakeholder/insights.php'],
                'messages' => ['label' => 'Messages', 'description' => 'Communicate with businesses, partners and the platform team', 'uri' => '/stakeholder/messages.php'],
                'settings' => ['label' => 'Settings', 'description' => 'Manage organisation settings, security and notification controls', 'uri' => '/stakeholder/settings.php'],
            ],
        ],
        'SUPER_ADMIN' => [
            'label' => 'Full platform control',
            'area' => 'admin',
            'dashboard_uri' => '/admin/dashboard.php',
            'modules' => [
                'overview' => ['label' => 'Dashboard', 'description' => 'Full platform overview including users, activity and system health', 'uri' => '/admin/dashboard.php'],
                'profile' => ['label' => 'Admin Profile', 'description' => 'Manage administrator identity, role and security settings', 'uri' => '/admin/profile.php'],
                'users' => ['label' => 'Users', 'description' => 'View and manage all platform user accounts', 'uri' => '/admin/user.php'],
                'roles' => ['label' => 'Roles & Permissions', 'description' => 'Configure admin sub-roles and their permission assignments', 'uri' => '/admin/roles.php'],
                'verifications' => ['label' => 'Verifications', 'description' => 'Review and action all business verification requests', 'uri' => '/admin/verifications.php'],
                'verification-track' => ['label' => 'Verification Track', 'description' => 'Real-time tracking of the full verification pipeline', 'uri' => '/admin/verification-track.php'],
                'businesses' => ['label' => 'Businesses', 'description' => 'Full management of all business profiles on the platform', 'uri' => '/admin/businesses.php'],
                'investors' => ['label' => 'Investors', 'description' => 'Full management of all investor accounts and preferences', 'uri' => '/admin/investors.php'],
                'stakeholders' => ['label' => 'Stakeholders', 'description' => 'Full management of institutions, banks, hubs and partners', 'uri' => '/admin/stakeholders.php'],
                'opportunities' => ['label' => 'Opportunities', 'description' => 'Manage all investment opportunities and deal flow', 'uri' => '/admin/opportunities.php'],
                'uploads' => ['label' => 'Uploads', 'description' => 'Manage all uploaded documents and file records', 'uri' => '/admin/uploads.php'],
                'insights' => ['label' => 'Insights', 'description' => 'Manage platform reports, analytics and published updates', 'uri' => '/admin/insights.php'],
                'messages' => ['label' => 'Messages', 'description' => 'View all contact messages, inquiries and support requests', 'uri' => '/admin/messages.php'],
                'chatbot' => ['label' => 'Chatbot Logs', 'description' => 'Review AI chatbot conversation logs and support interactions', 'uri' => '/admin/chatbot.php'],
                'ai-assistants' => ['label' => 'AI Assistants', 'description' => 'Configure named AI assistants used across the platform', 'uri' => '/admin/ai-assistants.php'],
                'ai-tools' => ['label' => 'AI Tools', 'description' => 'Manage AI tool settings and chatbot behaviour', 'uri' => '/admin/ai-tools.php'],
                'legal' => ['label' => 'Legal Documents', 'description' => 'Manage terms, privacy notice and legal consent pages', 'uri' => '/admin/legal.php'],
                'settings' => ['label' => 'System Settings', 'description' => 'Configure platform-wide settings, registration and upload limits', 'uri' => '/admin/settings.php'],
            ],
        ],
        'VERIFICATION_ADMIN' => [
            'label' => 'Verification team',
            'area' => 'admin',
            'dashboard_uri' => '/admin/dashboard.php',
            'modules' => [
                'overview' => ['label' => 'Dashboard', 'description' => 'Overview of pending, active and completed verifications', 'uri' => '/admin/dashboard.php'],
                'profile' => ['label' => 'My Profile', 'description' => 'Manage own admin identity and contact information', 'uri' => '/admin/profile.php'],
                'verifications' => ['label' => 'Verifications', 'description' => 'Review business documents, readiness and verification status', 'uri' => '/admin/verifications.php'],
                'verification-track' => ['label' => 'Verification Track', 'description' => 'Real-time tracking of all verification cases in progress', 'uri' => '/admin/verification-track.php'],
                'businesses' => ['label' => 'Businesses', 'description' => 'View business profiles related to active verification cases', 'uri' => '/admin/businesses.php'],
                'uploads' => ['label' => 'Uploads & Documents', 'description' => 'Review uploaded files and supporting business documents', 'uri' => '/admin/uploads.php'],
                'messages' => ['label' => 'Messages', 'description' => 'Communicate with businesses and team regarding verifications', 'uri' => '/admin/messages.php'],
            ],
        ],
        'SUPPORT_ADMIN' => [
            'label' => 'Helpdesk / support team',
            'area' => 'admin',
            'dashboard_uri' => '/admin/dashboard.php',
            'modules' => [
                'overview' => ['label' => 'Dashboard', 'description' => 'Overview of open support requests and recent activity', 'uri' => '/admin/dashboard.php'],
                'profile' => ['label' => 'My Profile', 'description' => 'Manage own admin identity and contact information', 'uri' => '/admin/profile.php'],
                'users' => ['label' => 'Users', 'description' => 'Look up and assist with user account issues', 'uri' => '/admin/user.php'],
                'messages' => ['label' => 'Messages', 'description' => 'Manage support inquiries, contact messages and follow-ups', 'uri' => '/admin/messages.php'],
                'chatbot' => ['label' => 'Chatbot Logs', 'description' => 'Review chatbot conversations to identify support issues', 'uri' => '/admin/chatbot.php'],
                'businesses' => ['label' => 'Businesses', 'description' => 'Look up business profiles to assist with user queries', 'uri' => '/admin/businesses.php'],
                'investors' => ['label' => 'Investors', 'description' => 'Look up investor accounts to assist with user queries', 'uri' => '/admin/investors.php'],
                'stakeholders' => ['label' => 'Stakeholders', 'description' => 'Look up institutional accounts to assist with user queries', 'uri' => '/admin/stakeholders.php'],
            ],
        ],
        'FINANCE_ADMIN' => [
            'label' => 'Finance / treasury team',
            'area' => 'admin',
            'dashboard_uri' => '/admin/dashboard.php',
            'modules' => [
                'overview' => ['label' => 'Dashboard', 'description' => 'Overview of financial activity, deals and platform transactions', 'uri' => '/admin/dashboard.php'],
                'profile' => ['label' => 'My Profile', 'description' => 'Manage own admin identity and contact information', 'uri' => '/admin/profile.php'],
                'businesses' => ['label' => 'Businesses', 'description' => 'Review business financial profiles and investment readiness', 'uri' => '/admin/businesses.php'],
                'investors' => ['label' => 'Investors', 'description' => 'Review investor accounts, ticket sizes and deal preferences', 'uri' => '/admin/investors.php'],
                'opportunities' => ['label' => 'Opportunities', 'description' => 'Monitor investment deals, funding requests and pipeline status', 'uri' => '/admin/opportunities.php'],
                'uploads' => ['label' => 'Uploads', 'description' => 'Review financial documents and uploaded business records', 'uri' => '/admin/uploads.php'],
                'insights' => ['label' => 'Insights', 'description' => 'Access financial reports, analytics and data summaries', 'uri' => '/admin/insights.php'],
                'messages' => ['label' => 'Messages', 'description' => 'Manage finance-related inquiries and communications', 'uri' => '/admin/messages.php'],
            ],
        ],
        'CONTENT_ADMIN' => [
            'label' => 'Content / editorial team',
            'area' => 'admin',
            'dashboard_uri' => '/admin/dashboard.php',
            'modules' => [
                'overview' => ['label' => 'Dashboard', 'description' => 'Overview of published content, uploads and platform activity', 'uri' => '/admin/dashboard.php'],
                'profile' => ['label' => 'My Profile', 'description' => 'Manage own admin identity and contact information', 'uri' => '/admin/profile.php'],
                'opportunities' => ['label' => 'Opportunities', 'description' => 'Create, edit and manage published investment opportunities', 'uri' => '/admin/opportunities.php'],
                'uploads' => ['label' => 'Uploads', 'description' => 'Manage media files, documents and uploaded platform content', 'uri' => '/admin/uploads.php'],
                'insights' => ['label' => 'Insights', 'description' => 'Publish and manage reports, updates and analytics content', 'uri' => '/admin/insights.php'],
                'ai-assistants' => ['label' => 'AI Assistants', 'description' => 'Configure the names, personas and behaviour of AI assistants', 'uri' => '/admin/ai-assistants.php'],
                'ai-tools' => ['label' => 'AI Tools', 'description' => 'Manage AI tool settings and chatbot response configuration', 'uri' => '/admin/ai-tools.php'],
                'chatbot' => ['label' => 'Chatbot Logs', 'description' => 'Review chatbot conversations and content accuracy', 'uri' => '/admin/chatbot.php'],
                'legal' => ['label' => 'Legal Documents', 'description' => 'Edit and publish terms, privacy notice and consent pages', 'uri' => '/admin/legal.php'],
                'messages' => ['label' => 'Messages', 'description' => 'Manage content-related inquiries and editorial communications', 'uri' => '/admin/messages.php'],
            ],
        ],
        'PARTNERSHIP_ADMIN' => [
            'label' => 'Partnerships / BD team',
            'area' => 'admin',
            'dashboard_uri' => '/admin/dashboard.php',
            'modules' => [
                'overview' => ['label' => 'Dashboard', 'description' => 'Overview of partnership activity, deals and ecosystem connections', 'uri' => '/admin/dashboard.php'],
                'profile' => ['label' => 'My Profile', 'description' => 'Manage own admin identity and contact information', 'uri' => '/admin/profile.php'],
                'businesses' => ['label' => 'Businesses', 'description' => 'Browse and engage with business profiles for partnership activity', 'uri' => '/admin/businesses.php'],
                'investors' => ['label' => 'Investors', 'description' => 'Browse and engage with investor accounts for deal facilitation', 'uri' => '/admin/investors.php'],
                'stakeholders' => ['label' => 'Stakeholders', 'description' => 'Manage institutional relationships and coordination', 'uri' => '/admin/stakeholders.php'],
                'opportunities' => ['label' => 'Opportunities', 'description' => 'Monitor and support active investment opportunities and deals', 'uri' => '/admin/opportunities.php'],
                'insights' => ['label' => 'Insights', 'description' => 'Access reports and analytics to support partnership decisions', 'uri' => '/admin/insights.php'],
                'messages' => ['label' => 'Messages', 'description' => 'Manage partner communications and external outreach', 'uri' => '/admin/messages.php'],
            ],
        ],
        'ANALYTICS_ADMIN' => [
            'label' => 'Data / analytics team',
            'area' => 'admin',
            'dashboard_uri' => '/admin/dashboard.php',
            'modules' => [
                'overview' => ['label' => 'Dashboard', 'description' => 'Platform-wide activity summary and key metrics overview', 'uri' => '/admin/dashboard.php'],
                'profile' => ['label' => 'My Profile', 'description' => 'Manage own admin identity and contact information', 'uri' => '/admin/profile.php'],
                'insights' => ['label' => 'Insights', 'description' => 'Access and analyse all platform reports and published data', 'uri' => '/admin/insights.php'],
                'role-dashboard' => ['label' => 'Dashboard Registry', 'description' => 'Review all role-based dashboards and their data views', 'uri' => '/admin/dashboards.php'],
                'businesses' => ['label' => 'Businesses', 'description' => 'Read-only view of business data for analytical purposes', 'uri' => '/admin/businesses.php'],
                'investors' => ['label' => 'Investors', 'description' => 'Read-only view of investor data for analytical purposes', 'uri' => '/admin/investors.php'],
                'stakeholders' => ['label' => 'Stakeholders', 'description' => 'Read-only view of stakeholder data for analytical purposes', 'uri' => '/admin/stakeholders.php'],
                'opportunities' => ['label' => 'Opportunities', 'description' => 'Read-only view of deal flow and opportunity pipeline data', 'uri' => '/admin/opportunities.php'],
                'verifications' => ['label' => 'Verifications', 'description' => 'Read-only view of verification statistics and completion rates', 'uri' => '/admin/verifications.php'],
            ],
        ],
    ],
    'aliases' => [
        'admin' => 'SUPER_ADMIN',
        'super_admin' => 'SUPER_ADMIN',
        'verification_admin' => 'VERIFICATION_ADMIN',
        'support_admin' => 'SUPPORT_ADMIN',
        'finance_admin' => 'FINANCE_ADMIN',
        'content_admin' => 'CONTENT_ADMIN',
        'partnership_admin' => 'PARTNERSHIP_ADMIN',
        'analytics_admin' => 'ANALYTICS_ADMIN',
        'business' => 'business',
        'investor' => 'investor',
        'stakeholder' => 'stakeholder',
    ],
    'extra_uri_module_map' => [
        '/admin/permissions.php' => 'roles',
    ],
];
