-- RIETA Chatbot Tables
-- Optional manual SQL if installer is not used.

CREATE TABLE IF NOT EXISTS ai_assistants (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    assistant_key VARCHAR(80) NOT NULL UNIQUE,
    assistant_name VARCHAR(120) NOT NULL,
    assistant_role VARCHAR(180) NOT NULL,
    audience VARCHAR(80) NOT NULL DEFAULT 'all',
    description TEXT NULL,
    welcome_message TEXT NULL,
    welcome_message_sw TEXT NULL,
    support_email VARCHAR(180) NULL,
    is_enabled TINYINT(1) NOT NULL DEFAULT 1,
    display_order INT UNSIGNED NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS rieta_conversations (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id INT UNSIGNED NULL,
    session_id VARCHAR(128) NOT NULL,
    language VARCHAR(12) NOT NULL DEFAULT 'sw',
    status VARCHAR(40) NOT NULL DEFAULT 'open',
    current_topic VARCHAR(120) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS rieta_messages (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    conversation_id BIGINT UNSIGNED NULL,
    user_id INT UNSIGNED NULL,
    sender VARCHAR(40) NOT NULL DEFAULT 'user',
    language VARCHAR(12) NOT NULL DEFAULT 'sw',
    message MEDIUMTEXT NOT NULL,
    intent VARCHAR(120) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS rieta_support_requests (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    conversation_id BIGINT UNSIGNED NULL,
    user_id INT UNSIGNED NULL,
    full_name VARCHAR(180) NOT NULL,
    email VARCHAR(180) NOT NULL,
    phone VARCHAR(80) NOT NULL,
    subject VARCHAR(220) NULL,
    concern TEXT NOT NULL,
    language VARCHAR(12) NOT NULL DEFAULT 'sw',
    status VARCHAR(40) NOT NULL DEFAULT 'new',
    forwarded_to VARCHAR(180) NOT NULL DEFAULT 'support@unidagateway.co.tz',
    mail_sent TINYINT(1) NOT NULL DEFAULT 0,
    mail_error TEXT NULL,
    ip_address VARCHAR(64) NULL,
    user_agent TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS rieta_faq_items (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    question_sw VARCHAR(255) NOT NULL,
    question_en VARCHAR(255) NULL,
    answer_sw TEXT NOT NULL,
    answer_en TEXT NULL,
    intent_key VARCHAR(120) NOT NULL UNIQUE,
    category VARCHAR(120) NOT NULL DEFAULT 'General',
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    display_order INT UNSIGNED NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
